# Generated by Django 5.2.1 on 2025-05-26 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetMatchInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('liked', 'Liked'), ('matched', 'Matched'), ('skipped', 'Skipped')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_sent', to='pets.pet')),
                ('target_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to='pets.pet')),
            ],
            options={
                'unique_together': {('source_pet', 'target_pet')},
            },
        ),
    ]
